spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092 # Optional (default value)
      bindings:
        functional-in-0:
          destination: functional-input
          group: spring-cloud-stream-kafka-functional # Optional
          content-type: text/plain
        functional-out-0:
          destination: functional-output
          content-type: text/plain
#    function:
#      definition: functional;functional # ; allows multiple bindings